services:
  postgres:
    image: postgres:16-alpine
    container_name: geora-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: geora
    ports:
      - "5432:5432"
    volumes:
      - geora-postgres-data:/var/lib/postgresql/data

volumes:
  geora-postgres-data:

